global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.3:9091']

remote_write:
  - url: http://influxdb:8086/api/v1/prom/write?db=prometheus
